[openpasslite]
host = "0.0.0.0"
port = 2177
cors_origin = "*"
debug = false
logfile_path = "logs/openpasslite.txt"

[smartfields]
host = "0.0.0.0"
port = 2188
cors_origin = "*"
debug = false
logfile_path = "logs/smartfields.txt"

[wildwings]
host = "0.0.0.0"
port = 2199
cors_origin = "*"
debug = false
logfile_path = "logs/wildwings.txt"