version: '3.8'

services:
  openpasslite:
    build:
      context: ./services/openpasslite
      dockerfile: Dockerfile
    container_name: openpasslite
    ports:
      - "2177:2177"
    volumes:
      - ./config.toml:/app/config.toml:ro
      - ./logs:/app/logs
      - ./mission:/app/mission:ro
    environment:
      - PYTHONPATH=/app
    networks:
      - smartfield-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2177/"]
      interval: 30s
      timeout: 10s
      retries: 3

  smartfield:
    build:
      context: ./services/smartfields
      dockerfile: Dockerfile
    container_name: smartfield
    ports:
      - "2188:2188"
    volumes:
      - ./config.toml:/app/config.toml:ro
      - ./logs:/app/logs
      - ./mission:/app/mission:ro
    environment:
      - PYTHONPATH=/app
    networks:
      - smartfield-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2188/"]
      interval: 30s
      timeout: 10s
      retries: 3

  wildwings:
    build:
      context: ./services/wildwings
      dockerfile: Dockerfile
    container_name: wildwings
    ports:
      - "2199:2199"
    volumes:
      - ./config.toml:/app/config.toml:ro
      - ./logs:/app/logs
      - ./mission:/app/mission:ro
    environment:
      - PYTHONPATH=/app
    networks:
      - smartfield-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2199/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  smartfield-network:
    driver: bridge